all : 
	g++ -Wall -g -std=c++11 generator0.cc -o generator0
	g++ -Wall -g -std=c++11 generator1.cc -o generator1
	g++ -Wall -g -std=c++11 generator2.cc -o generator2
	g++ -Wall -g -std=c++11 generator3.cc -o generator3
	g++ -Wall -g -std=c++11 generator4.cc -o generator4
	g++ -Wall -g -std=c++11 generator5.cc -o generator5

clean :
	rm -f generator0
	rm -f generator1
	rm -f generator2
	rm -f generator3
	rm -f generator4
	rm -f generator5
	rm -f mys01
	rm -f mys02
	rm -f mys03
	rm -f mys04
	rm -f mys05
	rm -f mys06
	rm -f mys07
